version: '3.4'

services:
  elkstack:
    image: ${DOCKER_REGISTRY-}elkstack
    build:
      context: .
      dockerfile: ElkStack/Dockerfile
    container_name: webapi
    depends_on:
      - logstash
  logstash:
    image: ${DOCKER_REGISTRY-}logstash
    build:
      context: .
      dockerfile: Logstash/Dockerfile
    container_name: logstash
