version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    container_name: webapi
    depends_on:
      - logstash
  logstash:
    image: ${DOCKER_REGISTRY-}logstash
    build:
      context: .
      dockerfile: Logstash/Dockerfile
    container_name: logstash
